---
ID: "77d15d3c-6e14-4781-94e8-549104485b8a"
Parent: "09c1914c-1abc-4cd8-83b7-1f92d0c71918"
Template: "27fd9d20-18dc-4e07-bf2b-7c00d5dd0a69"
Path: /sitecore/content/FrasersRewards/Settings/Robots Settings
DB: master
SharedFields:
- ID: "375a10d1-51e9-4618-ab72-91d4b3e51537"
  Hint: Content
  Value: |
    User-agent: *
    Disallow: /sitecore
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180622T034035Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
