---
ID: "80525702-7953-4f92-8d64-7af355b6cb6b"
Parent: "b93d5bc5-8708-434d-b908-dd03b838d29a"
Template: "b93d5bc5-8708-434d-b908-dd03b838d29a"
Path: /sitecore/templates/Project/Common/Content Types/Folders/Style Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{72A6FF0E-A1DD-42EA-B38A-77D13EF856D9}"
- ID: "b0a67b2a-8b07-4e0b-8809-69f751709806"
  Hint: __Tracking
  Type: Tracking
  Value: |
    <tracking
      ignore="1" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180716T101659Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
