---
ID: "dbb91a61-ad67-4551-b455-d749fe699d88"
Parent: "84f57772-978b-4262-a88c-19e021500d06"
Template: "84f57772-978b-4262-a88c-19e021500d06"
Path: /sitecore/templates/Foundation/Theming/ParametersTemplate_RowStyle/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180720T090456Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
