---
ID: "cd85a6d7-b64a-45f6-b118-fb4f025becdb"
Parent: "019f8634-a79c-4724-ac41-80e3ed317a81"
Template: "a1e45b2d-4cf4-4f4a-b922-6ebb7175dd64"
Path: /sitecore/content/AnchorPoint/Settings/Header Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180803T081850Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
