---
ID: "abd750e0-c0e4-49d1-8e27-e367ac6d5d03"
Parent: "019f8634-a79c-4724-ac41-80e3ed317a81"
Template: "3bbefab1-43b0-40d2-bf07-570b873bf68f"
Path: /sitecore/content/AnchorPoint/Settings/Item Resolver Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180711T060248Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
