---
ID: "7f0867ba-7283-4214-8989-4d24978222e4"
Parent: "2a1e2f32-df3e-4b82-b6b9-4baa981da0f7"
Template: "2a1e2f32-df3e-4b82-b6b9-4baa981da0f7"
Path: /sitecore/templates/Feature/Blog/_BlogCategory/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180620T081926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "b61a7758-deb3-44d4-abf9-48d85d612c30"
      Hint: Key
      Value: $name
    - ID: "d1170e59-438b-4ff8-874d-0438dfe2ddf7"
      Hint: Value
      Value: $name
