---
ID: "d644723f-aada-4544-8631-7b0b2db566c6"
Parent: "ec4dd3f2-590d-404b-9189-2a12679749cc"
Template: "ec4dd3f2-590d-404b-9189-2a12679749cc"
Path: /sitecore/templates/Foundation/Dictionary/DictionaryEntry/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: wordprocessing/16x16/word_count.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180613T043456Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
