---
ID: "fd48b81c-66f7-492d-a894-92b61e38f3a2"
Parent: "a2eb3e9e-555b-4a1a-b3dc-43eef929eac4"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Feature/Search/_Search Settings
DB: master
SharedFields:
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Type: tree list
  Value: "{BCCFEBEA-DCCB-48FE-9570-6503829EC03F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180824T090423Z
