---
ID: "c7c9f39f-116c-4718-92b5-8e0013f03182"
Parent: "059b9ae5-4896-45a1-a650-c341b0107227"
Template: "059b9ae5-4896-45a1-a650-c341b0107227"
Path: /sitecore/templates/Project/FrasersProperty/Content Types/Mobile Navigation Link/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "125a4e47-7dc0-451f-b37b-2dd5176eafa9"
      Hint: IsTabPage
      Type: Checkbox
      Value: 1
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180817T095718Z
    - ID: "50f14a1e-3e83-4186-8a90-399b5c3bdd53"
      Hint: Navigation Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
