---
ID: "8e2203e5-5652-4730-9d6b-a8b01b86b043"
Parent: "d0d1af2c-2a67-4c7f-bf7f-09570fee7521"
Template: "06bf4651-240d-4dca-9830-ce4bc82782f6"
Path: /sitecore/templates/Branches/User Defined/FrasersProperty/Main Website/$name/Settings/Footer Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180813T065648Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
