---
ID: "75fa6290-e59e-49fc-bd8c-ae93b129229a"
Parent: "873e336f-5125-403c-b585-833f10c7054f"
Template: "873e336f-5125-403c-b585-833f10c7054f"
Path: /sitecore/templates/Foundation/Theming/ParametersTemplate_ColStyle/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180723T092209Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
