---
ID: "c17c028d-67da-4ac5-9f7a-f00ab0a6cef5"
Parent: "75b88333-2702-415d-9f7a-fe84771ae580"
Template: "75b88333-2702-415d-9f7a-fe84771ae580"
Path: /sitecore/templates/Project/Common/Content Types/Folders/Store Offer Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{13AC68BF-A202-4CE2-8E04-262987229AA3}"
- ID: "b0a67b2a-8b07-4e0b-8809-69f751709806"
  Hint: __Tracking
  Type: Tracking
  Value: |
    <tracking
      ignore="1" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180612T045801Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
