---
ID: "19d3cf57-2fab-4d29-af34-a90cf65f807b"
Parent: "f666a29e-a9c3-40fd-a3b8-cdae59d9f09d"
Template: "f666a29e-a9c3-40fd-a3b8-cdae59d9f09d"
Path: /sitecore/templates/Foundation/Import/ImportMap/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{58623B95-07DC-4F00-8D7A-337BF116FB54}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150703T144520Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150703T144520Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
