---
ID: "b7d4ee1a-8d0b-4916-9845-3d150dd5912c"
Parent: "72a6ff0e-a1dd-42ea-b38a-77d13ef856d9"
Template: "72a6ff0e-a1dd-42ea-b38a-77d13ef856d9"
Path: /sitecore/templates/Project/FrasersProperty/Content Types/Style/__Standard Values
DB: master
SharedFields:
- ID: "b0a67b2a-8b07-4e0b-8809-69f751709806"
  Hint: __Tracking
  Type: Tracking
  Value: |
    <tracking
      ignore="1" />
- ID: "cf1e34b0-27e7-4861-becd-c0bc58295f77"
  Hint: Class
  Value: $name
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180726T044420Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
