---
ID: "de836a76-c069-4971-9461-5b7311e1fbf3"
Parent: "d668aad6-791c-4db0-ab9f-d78b182b569a"
Template: "d668aad6-791c-4db0-ab9f-d78b182b569a"
Path: /sitecore/templates/Project/Common/Content Types/Folders/Banner Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{F99D38F2-8B19-461B-89FD-3ED8262CA199}"
- ID: "b0a67b2a-8b07-4e0b-8809-69f751709806"
  Hint: __Tracking
  Type: Tracking
  Value: |
    <tracking
      ignore="1" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180613T045334Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
