---
ID: "399d7813-7bc9-45c4-889d-b6d66b598d75"
Parent: "0f228f50-8120-4a0f-847c-dec8243f1028"
Template: "0f228f50-8120-4a0f-847c-dec8243f1028"
Path: /sitecore/templates/Feature/Search/ParametersTemplate_LatestPost/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180803T041530Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "a138be77-5be5-4de3-bd1c-b08a43f94392"
      Hint: IsCurrentSite
      Type: Checkbox
      Value: 1
