---
ID: "f4a87e6b-a251-48a1-b958-866b0bc6105a"
Parent: "e302f1e7-79f6-4c9e-88fb-279e9cd4f48f"
Template: "e302f1e7-79f6-4c9e-88fb-279e9cd4f48f"
Path: /sitecore/templates/Feature/Store/ParametersTemplate_StoreQuickFinder/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180727T083200Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
