---
ID: "701785c6-0553-4e5a-a430-cf54ea504204"
Parent: "74713dba-ac0d-4a12-bc9e-f607bb2c8ed1"
Template: "74713dba-ac0d-4a12-bc9e-f607bb2c8ed1"
Path: /sitecore/templates/Project/FrasersProperty/Content Types/Header/Social Link/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180702T045517Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
