---
ID: "d5d1f71b-105f-4ee9-9bf3-4e73da2b19c1"
Parent: "c0666526-56c5-42fa-a8cf-f70fbfda0508"
Template: "c0666526-56c5-42fa-a8cf-f70fbfda0508"
Path: /sitecore/templates/Project/FrasersProperty/Content Types/Header/Social Links/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{74713DBA-AC0D-4A12-BC9E-F607BB2C8ED1}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180702T045523Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
