---
ID: "abc21280-d70d-40e7-b65c-8d0cebff0f9c"
Parent: "2db06657-1cc1-45a3-8638-7d4548f1fb25"
Template: "2db06657-1cc1-45a3-8638-7d4548f1fb25"
Path: /sitecore/templates/Feature/Multisite/ParametersTemplate_Malls/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180803T065620Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
