---
ID: "a7d6ce0c-3885-4ca0-bc00-041477a574d0"
Parent: "cdc2a4e9-1c55-4f15-8218-9167e69c6adc"
Template: "cdc2a4e9-1c55-4f15-8218-9167e69c6adc"
Path: /sitecore/templates/Foundation/Import/MapsFolder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{3DD41A19-1F84-4E83-A657-930ADD646ADB}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160903T220423Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160903T220423Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
