---
ID: "d9e28145-7204-4949-9e4a-5b405953f2f6"
Parent: "17e7ce43-ffac-4c8d-8904-0eb2597e179d"
Template: "8f0cbbf0-73d3-4cc1-97d3-45df9a2ff358"
Path: /sitecore/content/FrasersRewards/Home/Services
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 250
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190120T201602Z
    - ID: "50f14a1e-3e83-4186-8a90-399b5c3bdd53"
      Hint: Navigation Title
      Value: Services
    - ID: "e81c5d1d-e1de-47e7-a5c1-d3c77db7e75b"
      Hint: Link
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{EED3A08D-8D1A-4906-A624-17660167ECA2}" />
