---
ID: "b0e4faf2-b8d9-4e96-a6df-2fc99bf1b8ec"
Parent: "66d95284-43f6-46b7-950d-1ce4ef64d772"
Template: "66d95284-43f6-46b7-950d-1ce4ef64d772"
Path: /sitecore/templates/Project/FrasersProperty/Content Types/Store/Alphabet/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180717T091041Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
