---
ID: "d79fd056-7402-4b34-86c6-2dac7232c958"
Parent: "d9b8d336-9076-4601-8150-fda2d532df62"
Template: "a1e45b2d-4cf4-4f4a-b922-6ebb7175dd64"
Path: /sitecore/templates/Branches/User Defined/FrasersProperty/Mall Website/$name/Settings/Header Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180803T081850Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
