---
ID: "2e0c0662-bdf8-46e1-a1e4-00c143cde545"
Parent: "5fc3377b-3ccb-4551-b42e-7a317ca34149"
Template: "5fc3377b-3ccb-4551-b42e-7a317ca34149"
Path: /sitecore/templates/Feature/Store/ParametersTemplate_StoreSearchCriteria/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180724T074355Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
